GET http://127.0.0.1:5000/cf/users_based/633b30e4edfee7840d1006c6
Content-Type: application/json

{
    
}

###

GET http://127.0.0.1:5000//cb/recommend_by_user/633b30e4edfee7840d1006c6
Content-Type: application/json

{
    
}

###
 env\Scripts\activate.bat
 $env:FLASK_APP="index.py"
 $env:FLASK_ENV="development"